### ISSUE TITLE
mld2p4-2.1.1 compiler error

### ISSUE THREAD

**Issue by sagitter** [sfilippone/mld2p4-2#2]
Hi all.

`mld2p4-2.1.1-rc1` does not compile on Fedora 27 with following error:

```
make[1]: Entering directory '/home/sagitter/rpmbuild/BUILD/mld2p4-2-2.1.1-rc1/mld2p4-2-2.1.1-rc1/mlprec'
gfortran -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,--as-needed -fPIC -I/usr/include/openblas  -I. -I../include -I/usr/lib64/gfortran/modules/psblas3 -I/usr/include/psblas3 -DHAVE_SLU_ -DHAVE_UMF_ -DHAVE_MUMPS_  -DHAVE_LAPACK -DHAVE_MOLD -DHAVE_EXTENDS_TYPE_OF -DHAVE_SAME_TYPE_AS -DHAVE_FINAL -DHAVE_ISO_FORTRAN_ENV -DHAVE_FLUSH_STMT -DHAVE_VOLATILE -DSERIAL_MPI -DMPI_MOD   -c mld_s_mumps_solver.F90 -o mld_s_mumps_solver.o
mld_s_mumps_solver.F90:54:6:

   use smumps_struc_def
      1
Fatal Error: Can't open module file 'smumps_struc_def.mod' for reading at (1): No such file or directory
compilation terminated.
make[1]: *** [../Make.inc:113: mld_s_mumps_solver.o] Error 1
```

Full build log: https://paste.fedoraproject.org/paste/dFT-wiAdWP~UilzWFYkYQw
config.log: https://paste.fedoraproject.org/paste/B0nrL9OSrYS9G4UQRAgeAg

Compiler used:

```
$ gcc --version
gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by sfilippone** [comment]
Looks strange, can I see the generated Make.inc file? 
The config shows that dmumps is recognised, but at compile time the include flag is not there???

**Comment by sagitter** [comment]
Make.inc: https://paste.fedoraproject.org/paste/ZoIeXm0baGzhQx5W7ULjJg

**Comment by sfilippone** [comment]
Ok, the MUMPSFLAG line in Make.inc is missing  
-I/usr/lib64/gfortran/modules/mpich/MUMPS-5.1.2
which is strange because inside config.log it is clear that the configure script did identify that directory. 
Will get back to you asap

**Comment by sagitter** [comment]
`-I/usr/lib64/gfortran/modules/mpich/MUMPS-5.1.2` is a MPI library path. Why should it be required for compiling the serial `mld2p4` library?

**Comment by sfilippone** [comment]
Right. I have reproduced the issue, will get back to you asap

**Comment by sfilippone** [comment]
Ok, simpler than I expected. I had changed the configure script in the same spirit as the install procedure, i.e. separating the C include directory from the Fortran modules directory; in other words, you need the configure options
--with-mumps="-ldmumps -lcmumps -lsmumps -lzmumps" --with-mumpsmoddir=/usr/lib64/gfortran/modules/MUMPS-5.1.2  --with-mumpsincdir=/usr/include/MUMPS
My previous (silly) remark was because I only had the mpich version of mumps on my laptop,
However I am testing for a runtime error which is related to the --enable-serial option, since the exact same test case  does work from the parallel version run with 1 process. Stay tuned.

**Comment by sfilippone** [comment]
Moreover, I have to change a few bits of the configure script for the --with-mumpslibdir option.

**Comment by sfilippone** [comment]
Testing in serial mode, I am getting this error from MUMPS 
```
 mumps_bld: +++++>           0           0
 Unrecoverable Error in DMUMPS initialization:  MPI is not running.
 calling mumps N,nz,nz_loc        1703       92347       92347
 Unrecoverable Error in DMUMPS initialization:  MPI is not running.
 
Preconditioner: ML-VCYCLE-FBGS-R-UMF
Preconditioner time:  4.81418E+00
```
Now, I had specified running with the serial option as in 
[config.log](https://github.com/sfilippone/mld2p4-2/files/1670354/config.log)

with the links step being
```
gfortran  mld_d_pde3d.o  data_input.o -o mld_d_pde3d -L../../lib -lpsb_krylov -lmld_prec -lpsb_prec -lpsb_krylov -lpsb_prec -lpsb_util -lpsb_base -L/usr/local/PSBLAS/DEV/sys-serial-dbg/lib	 -ldmumps -lcmumps -lsmumps -lzmumps    -lumfpack -lamd    -lsatlas -L/usr/lib64/atlas -lmetis  -lamd  
```
and yet this is what ldd tells me
```
sfilippo@localhost runs]$ ldd mld_d_pde3d
	linux-vdso.so.1 (0x00007fff6f5e4000)
	libdmumps-5.1.2.so => /usr/lib64/mpich/lib/libdmumps-5.1.2.so (0x00007fdad65de000)
	libcmumps-5.1.2.so => /usr/lib64/mpich/lib/libcmumps-5.1.2.so (0x00007fdad625f000)
	libsmumps-5.1.2.so => /usr/lib64/mpich/lib/libsmumps-5.1.2.so (0x00007fdad5ee8000)
	libzmumps-5.1.2.so => /usr/lib64/mpich/lib/libzmumps-5.1.2.so (0x00007fdad5b68000)
	libumfpack.so.5 => /lib64/libumfpack.so.5 (0x00007fdad5896000)
	libamd.so.2 => /lib64/libamd.so.2 (0x00007fdad568a000)
```
despite having both the mpich and serial versions of mumps installed:
```
sfilippo@localhost runs]$ dnf list MUMPS*
Last metadata expiration check: 3 days, 9:27:31 ago on Wed 24 Jan 2018 08:16:25 AM GMT.
Installed Packages
MUMPS.x86_64                                                                                5.1.2-2.fc27                                                     @sagitter-psblas
MUMPS-common.noarch                                                                         5.1.2-2.fc27                                                     @sagitter-psblas
MUMPS-devel.x86_64                                                                          5.1.2-2.fc27                                                     @sagitter-psblas
MUMPS-mpich.x86_64                                                                          5.1.2-2.fc27                                                     @sagitter-psblas
MUMPS-mpich-devel.x86_64                                                                    5.1.2-2.fc27                                                     @sagitter-psblas

```
Any ideas?

**Comment by sfilippone** [comment]
The updated configry is available at https://github.com/sfilippone/mld2p4-2/commit/147f37040d7f814a6f299b1827606c15747ad32b

**Comment by sagitter** [comment]
>https://github.com/sfilippone/mld2p4-2/issues/2#issuecomment-361001314

This happens if you had ran MPI script before.
MUMPS libraries are correctly linked to me.

RPMs from Copr are useless now, all libraries PSBLAS and mld2p4 are in official repository.

>The updated configry is available at 147f370

Your latest changes are working.

**Comment by sfilippone** [comment]
Right, I had a rogue module loaded. 
Will put in some further changes to doc & license and then put on tag -rc2 
T

**Comment by sfilippone** [comment]
I put in a few more changes to the configure machinery and declared -rc2.
Could you please check it still works? 
I plan to add a change to all example files, to enable passing the input control file as either standard input or as a filename on the command line, and that will be v 2.1.1

**Comment by sagitter** [comment]
> Could you please check it still works?

Correctly compiled: https://kojipkgs.fedoraproject.org//work/tasks/3658/24573658/build.log
